spotify_tracks:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "md:spotify"
      extensions:
        - httpfs
      settings:
        s3_region: us-east-1
      secrets:
        - type: s3
          provider: credential_chain

