version: 2

sources:
  - name: spotify_raw
    schema: raw
    tables:
      - name: raw__album_images
      - name: raw__albums
      - name: raw__artist_albums
      - name: raw__artist_genres
      - name: raw__artist_images
      - name: raw__artist_redirects
      - name: raw__artists
      - name: raw__available_markets
      - name: raw__playlist_images
      - name: raw__playlist_tracks
      - name: raw__playlists
      - name: raw__track_artists
      - name: raw__track_audio_features
      - name: raw__track_files
      - name: raw__tracks
      - name: raw__audiobook_chapters
      - name: raw__audiobooks
      - name: raw__show_episodes
      - name: raw__shows
